env:
  es6: true
  node: true
extends: 'eslint:recommended'
parserOptions:
  ecmaVersion: 2018
rules:
  indent: 
    - error
    - 4
    - SwitchCase: 1
      ignoreComments: true
  linebreak-style: [error, windows]
  semi: [error, never]

  # quotes are currently not consistent
  quotes: off

  no-unused-vars: warn
  no-console: off