env:
  es6: true
  node: true
#extends: 'eslint:recommended'
parserOptions:
  ecmaVersion: 2018
rules:
  indent: 
    - error
    - 4
    - SwitchCase: 1
      ignoreComments: true
  linebreak-style: [error, windows]
  # currently not consistent
  quotes: off
  semi: [error, never]
  no-console: off